pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/<username>/ecommerce-app.git'
            }
        }
        stage('Build and Push Docker Images') {
            steps {
                script {
                    sh 'docker build -t <region>.icr.io/<namespace-name>/ecommerce-app .'
                    sh 'docker push <region>.icr.io/<namespace-name>/ecommerce-app'
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh """
                    kubectl apply -f k8s/deployment.yaml
                    kubectl apply -f k8s/monitoring-deployment.yaml
                    """
                }
            }
        }
    }
}